Issue 4
AlexeyVatolin/liquid-log pull request #5
Opened 2017-11-14 13:55 UTC by AlexeyVatolin

@ykalemi Сделал задание "Общие интерфейсы для парсеров". Создал интерфейсы DataParser, TimeParser, разделил сами парсеры и создаваемые ими данные. Переписал тесты, чтобы они работали в изменившемся коде. Жду предложений по улучшению

2017-11-14 19:26 UTC, ykalemi requested changes
Направление правильное, хорошо, что отделили данные от парсеров. Но TopParser у вас теперь не работает

2017-11-14 19:26 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/Parser.java
> +                dataParser = new GenericParser(new GCParser());
а зачем здесь GenericParser?

2017-11-14 19:26 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/time_parsers/TopTimeParser.java
> +        return 0L;
посмотрите файл Top, он несколько отличается от двух других файлов. Дата там не в каждой строке. Ваш код это не учитывает

2017-11-14 19:26 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/Parser.java
> +                    dataParser.setDataSet(dataSet);
могу предложить простое решение - добавьте dataSet в сигнатуру метода parseLine у DataParser-а. Тогда не нужен будет отдельный метод и не надо будет хранить этот сет в парсере

2017-11-15 07:10 UTC, AlexeyVatolin commented on src/main/java/ru/naumen/perfhouse/parser/Parser.java
> +                dataParser = new GenericParser(new GCParser());
Согласен, не нужен

2017-11-15 07:15 UTC, AlexeyVatolin commented on src/main/java/ru/naumen/perfhouse/parser/Parser.java
> +                    dataParser.setDataSet(dataSet);
У меня так было сделано поначалу, но Top парсер не работал. В текущем код я сохраняю dataSet и, если в строке нет времени, сохраняю в него результаты парсинга. Это достаточно похоже на код, который был в оригинале. Для остальных парсеров и правда можно передавать dataSet как параметр метода, но тогда придется писать для Top отдельный цикл обработки. Я тестировал, все три парсера работают и строят такие же графики, как и раньше. График для Top парсера на текущем коде
![image](https://user-images.githubusercontent.com/8269808/32823212-0e244888-c9fe-11e7-98cc-68ba3e2291f4.png)

2017-11-16 08:33 UTC, ykalemi requested changes
Задача в целом сделана правильно зачтена, но я хотел бы небольших изменений - или их всё равно придётся делать в будущих задачах.

2017-11-16 08:33 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/Parser.java
> +                    dataParser.setDataSet(dataSet);
Да, я понял теперь как это работает.

Да, есть два варианта - или парсер времени в Top хранит последнее время, или парсер данных Top хранит текущий DataSet. Оба имеют право на существование.

Но я бы предложил всё-таки переработать код. Как минимум, это не сходится с дальнейшими задачами :)

Если передавать dataSet в сигнатуру parseLine, то не обязательно писать свой цикл обработки - надо просто изменить парсер времени в Top таким образом, чтобы он возвращал последнее распарсенное им время. Тогда в общем цикле мы для одно времени будем автоматически получать один и тот же DataSet.

2017-11-16 08:35 UTC, ykalemi commented on src/main/resources/application.properties
> +influx.host=http://wildfly-influxdb-liquidlog.148.251.87.70.nip.io/
у вас попали локальные конфиги в коммит. Чтобы этого не происходило, достаточно скопировать этот конфиг на своей машине в папку `config/` - эта папка уже заигнорена для гита, и не будет добавляться в коммиты. При этом, конфиг в этой папке имеет приоритет над данным файлом в самом проекте

2017-11-16 11:43 UTC, AlexeyVatolin commented on src/main/resources/application.properties
> +influx.host=http://wildfly-influxdb-liquidlog.148.251.87.70.nip.io/
Нехорошо получилось :) Отменил коммит, в котором пароль попал в открытый доступ и сделал как вы сказали

2017-11-16 11:45 UTC, AlexeyVatolin commented
Отличная идея с сохранением времени в Top парсере, мне как раз ее не хватало. Переписал код и протестировал, все работает

2017-11-16 12:50 UTC, ykalemi approved these changes
да, вроде всё зашибись

2017-11-16 12:50 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/data_parsers/GCParser.java
> +    private Pattern gcExecutionTime = Pattern.compile(".*real=(.*)secs.*");
кстати, это же константа? Тогда `static final`

2017-11-16 13:15 UTC, merged