Issue 5 Меньшее потребление памяти при парсинге
AlexeyVatolin/liquid-log pull request #6
Opened 2017-11-20 05:45 UTC by AlexeyVatolin

@ykalemi Уменьшил потребление памяти при парсинге, теперь каждый DataSet сохраняется как только он был заполнен.  Покрыл тестами новый класс DataStorage, остались без покрытия только строки вывода лога на экран. 
![image](https://user-images.githubusercontent.com/8269808/33003928-a8e5f24c-cddf-11e7-9a3d-4b4fd745d2a5.png)

2017-11-20 06:35 UTC, ykalemi requested changes

2017-11-20 06:35 UTC, ykalemi commented on src/test/java/ru/naumen/DataStorageTest.java
> +    {
не стоит помещать логику в конструктор теста. Лучше пользоваться общепринятыми методами JUnit. Всё это вполне помещается в метод `@Before`

2017-11-20 06:35 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +    private InfluxDAOImpl influxDAO;
Более корректно всегда использовать интерфейсы при их наличии. Таким образом, вы не зависите от реализации и полагаетесь только на контракт

2017-11-20 06:35 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/influx/DataStorage.java
> +public class DataStorage {
С DataStorage есть проблема - он же синглтон. Но при этом хранит состояние каждого парсинга. При многопоточной обработке это всё сломается, конечно.

Для простоты я мог бы предложить пока не делать этот класс spring-бином, а создавать его на каждую обработку. (ну или вы сами можете придумать более корректное решение)

2017-11-20 06:35 UTC, ykalemi commented on src/test/java/ru/naumen/DataStorageTest.java
> +    private InfluxDAO influxDAOMock;
Хочу, чтобы вы написали такой тест:
1. Вызвать dataStorage.get(1) и dataStorage.get(2)
2. Проверить, сколько раз сохранились данные

2017-11-20 12:51 UTC, ykalemi requested changes
минорные замечания по тесту

2017-11-20 12:51 UTC, ykalemi commented on src/test/java/ru/naumen/DataStorageTest.java
> +    private static InfluxDAO influxDAOMock;
а почему понадобилось делать static? Тут может быть другой прикол - у вас какие-то моки будут шариться между тестами, и в каком-нибудь новом тесте будут возвращать неожиданное количество вызовов.

лучше все моки убрать в `@Before`, `@BeforeClass` мне кажется вам совсем не нужен. dbName вообще можете сделать константой

2017-11-20 12:53 UTC, ykalemi requested changes
Хотя нет, не совсем минорные. Я просил вот такой тест написать:

> Вызвать dataStorage.get(1) и dataStorage.get(2)
> Проверить, сколько раз сохранились данные

потому что у вас в коде ошибка. И этим тестом её можно найти

2017-11-21 06:31 UTC, AlexeyVatolin commented
Не совсем понимаю как сделать этот тест. Я написал тексты такого вида:
`verify(influxDAOMock, times(1)).storeTop(batchPoints, dbName, 1, dataSet.getTopData());`
По сути они как раз проверяют сколько раз сохранялись данные.
Баг в том, что последний DataSet никогда не сохранится?

2017-11-21 06:38 UTC, ykalemi commented
Да, баг в этом. Вместо конкретного dataSet.getTopData() можно использовать что-то вроде Mockito.any().

Ну или вам надо доделать последний тест

```
//when
DataSet dataSet = dataStorage.get(1);
dataParser.parseLine(dataSet, gcLogLine);
DataSet dataSetWithKeyTwo = dataStorage.get(2);

//then
verify(influxDAOMock, times(1)).storeTop(batchPoints, dbName, 1, dataSet.getTopData());
verify(influxDAOMock, times(1)).storeTop(batchPoints, dbName, 1, dataSetWithKeyTwo.getTopData());
```

2017-11-21 06:50 UTC, AlexeyVatolin commented
Про Mockito.any() знаю, но хотелось проверить что вызывается именно нужное сохранение.
Будет ли хорошим решением проблемы написать функцию, которая должна будет вызываться после всех операция с базой данных и сохранять последний DataSet? Или лучше сохранять DataSet в базу перед каждым get()?

2017-11-21 07:09 UTC, ykalemi commented
Ну я когда решал эту задачу, то просто сделал отдельный метод save, который вызывал после обработки всего файла. Так что первый вариант с моей точки зрения - ок

2017-11-21 07:52 UTC, AlexeyVatolin commented
Мне он тоже кажется более логичным, во втором неоправданно повышается количество запросов к базе. Единственное что нет причин, которые бы заставили писать везде после работы с данными save(), можно случайно забыть про это.

2017-11-21 08:04 UTC, ykalemi commented
Ну сейчас в приложении только одно место, где идёт работа с данными и других не предполагается. А чтобы при каких-то рефакторингах случайно не удалить save - должен быть тест, который будет фиксировать это поведение

2017-11-21 08:06 UTC, ykalemi approved these changes

2017-11-27 13:13 UTC, merged